name: Update BTIS daily

on:
  schedule:
    - cron: '15 13 * * *'  # 13:15 UTC daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Run updater
        env:
          GLASSNODE_API_KEY: ${{ secrets.GLASSNODE_API_KEY }}
        run: |
          python scripts/btis.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/btis.json
          git commit -m "chore: update BTIS ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "No changes to commit"
          git push
